# If the docker compose doesn't work because of the version, you can use the following command to run the container
# docker compose down -v
# docker compose up -d

services:
  postgres:
    image: postgres:latest
    container_name: boilerplate-postgres
    environment:
      POSTGRES_DB: boilerplate-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: boilerplate-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  postgres_data:
  redis_data:
